[package]
name = "useless-rs"
version = "0.1.0"
authors = ["Chandler Wilkerson <cwilkers@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.55", default-features = false }
